#!/usr/bin/env python3
"""Generate docs/FILE_INVENTORY.md — one-line purpose for every tracked source file.

Usage (from repo root or backend):
  python scripts/generate_file_inventory.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "FILE_INVENTORY.md"

SKIP_DIRS = {
    ".git",
    ".venv",
    "node_modules",
    "dist",
    "__pycache__",
    ".pytest_cache",
    "storage",
    "legacy",
}

MODULE_HINTS = {
    "backend/app/publications": "Publications (Scholar sync, faculty, student pubs, exports)",
    "backend/app/projects": "Projects and Theses (BTP/IP) + SDG tagging",
    "backend/app/copo": "CO-PO attainment engine and APIs",
    "backend/app/course_allocation": "Course / faculty allocation",
    "backend/app/auth": "Authentication, JWT, user admin",
    "backend/app/documents": "Meeting minutes + RAG",
    "backend/app/budget": "Budget module",
    "backend/app/analytics": "Analytics dashboards",
    "backend/app/notifications": "Notifications + requirement tracker",
    "backend/app/awards": "Faculty awards",
    "backend/app/contributions": "Faculty contributions",
    "backend/app/llm": "Local LLM insights",
    "backend/app/ece_eve_projects": "ECE/EVE projects",
    "backend/alembic": "Database migrations",
    "frontend/src/modules/publications": "Publications UI",
    "frontend/src/modules/projects": "Projects and Theses UI",
    "frontend/src/modules/copo": "CO-PO UI",
    "frontend/src/modules/course_allocation": "Course allocation UI",
    "docs": "Handoff documentation",
    "deploy": "Production process managers / Nginx",
    "data": "Runtime assets and SQL bootstrap",
}


def guess_module(rel: str) -> str:
    for prefix, label in MODULE_HINTS.items():
        if rel.replace("\\", "/").startswith(prefix):
            return label
    return "Shared / root"


def guess_purpose(path: Path, rel: str) -> str:
    name = path.name
    if name == "README.md":
        return "Module or project overview"
    if name.endswith(".md"):
        return "Documentation"
    if "alembic/versions" in rel.replace("\\", "/"):
        return f"Alembic migration `{path.stem}`"
    if name == "router.py" or name.endswith("router.py"):
        return "HTTP API routes"
    if name.endswith("Page.tsx"):
        return "React page / screen"
    if "services/" in rel.replace("\\", "/") and name.endswith(".py"):
        return "Domain service / business logic"
    if "models/" in rel.replace("\\", "/") and name.endswith(".py"):
        return "SQLAlchemy / Pydantic models"
    if name == "main.py":
        return "FastAPI application entrypoint"
    if name == "App.tsx":
        return "Frontend route map"
    if name == "AppLayout.tsx":
        return "Top navigation shell"
    if name.endswith(".tsx") or name.endswith(".ts"):
        return "Frontend TypeScript module"
    if name.endswith(".py"):
        return "Python module"
    if name.endswith(".yml") or name.endswith(".yaml"):
        return "Deploy / compose configuration"
    if name.endswith(".sql"):
        return "SQL bootstrap or maintenance script"
    if name.endswith(".csv") or name.endswith(".xlsx"):
        return "Data / template asset"
    if name.endswith(".cjs") or name.endswith(".json"):
        return "Tooling / package configuration"
    return "Project file"


def iter_files() -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel_parts = path.relative_to(ROOT).parts
        if any(part in SKIP_DIRS for part in rel_parts):
            continue
        if path.suffix in {".pyc", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico"}:
            continue
        if path.name == "900A0600":
            continue
        files.append(path)
    return sorted(files, key=lambda p: str(p.relative_to(ROOT)).lower())


def main() -> None:
    lines = [
        "# File inventory",
        "",
        "Generated by `backend/scripts/generate_file_inventory.py`.",
        "Regenerate after large refactors. Prefer the module guides in `docs/` for behavior;",
        "use this table to locate the file that owns a concern.",
        "",
        "| Path | Module | Purpose |",
        "|------|--------|---------|",
    ]
    for path in iter_files():
        rel = path.relative_to(ROOT).as_posix()
        lines.append(f"| `{rel}` | {guess_module(rel)} | {guess_purpose(path, rel)} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(lines) - 7} files)")


if __name__ == "__main__":
    main()
