# -*- coding: utf-8 -*-
"""ECE-orignal-updated

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJCGeYl8b_kYrL_8UJD4XtL5ls2O5Zpa
"""

# # Step 1: Mount Google Drive
# from google.colab import drive
# drive.mount('/content/drive', force_remount=True)

# Step 2: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import os
import sys
import datetime
import re
from difflib import SequenceMatcher

from app.copo.services.mapping_service import course_title_matches

# Display uncropped output for pandas
pd.set_option('display.max_columns', None)

def normalize_evaluation_name(value):
    """Normalize evaluation labels for matching across case/spacing variants."""
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", "", str(value).strip()).upper()


def normalize_group_key(value) -> str:
    """Normalize parent group labels (case/space/punctuation tolerant)."""
    raw = normalize_evaluation_name(value)
    raw = raw.split(".")[0]
    return re.sub(r"[^A-Z0-9]", "", raw)


def _group_name_parts(group_key: str) -> tuple[str, str]:
    m = re.match(r"^([A-Z_]+?)(\d+)?$", group_key or "")
    if not m:
        return (group_key or "", "")
    return (m.group(1) or "", m.group(2) or "")


def _canonical_assessment_id(col_name: str, group_key: str) -> str:
    col = str(col_name).strip()
    suffix_match = re.match(r"^(.+?)(\.\d+)$", col)
    if suffix_match:
        return f"{group_key}{suffix_match.group(2)}"
    return group_key


def co_cell_empty(value) -> bool:
    if pd.isna(value):
        return True
    return str(value).strip().lower() in ("", "nan", "none", "null", "n/a", "-", "—")


def is_bonus_assessment_column(name: str) -> bool:
    n = str(name).strip().lower()
    if n == "bonus":
        return False
    if n.endswith("_bonus"):
        return True
    return n.startswith("bonus")


def split_co_labels(value) -> list[str]:
    """Turn a CO cell into CO1/CO2 labels; blank/NaN → []."""
    if co_cell_empty(value):
        return []
    labels: list[str] = []
    for part in str(value).split(","):
        part = part.strip()
        match = re.fullmatch(r"CO(\d+)", part, re.IGNORECASE)
        if match:
            labels.append(f"CO{int(match.group(1))}")
    return labels


def get_co_row_key(df: pd.DataFrame):
    for k in df.index:
        label = str(k).strip().upper()
        if label in ("CO", "CO TO BE ENTERED"):
            return k
    return None


def get_max_marks_row_key(df: pd.DataFrame):
    for k in df.index:
        if str(k).strip().upper() in ("MAX_MARKS", "MAX MARKS", "MARKS"):
            return k
    return None


def _max_marks_numeric(df: pd.DataFrame, max_marks_key, col) -> float:
    if max_marks_key is None:
        return float("-inf")
    val = df.loc[max_marks_key, col]
    try:
        if pd.isna(val):
            return float("-inf")
        return float(val)
    except (TypeError, ValueError):
        return float("-inf")


def columns_mapped_to_co(df: pd.DataFrame, co_key, target_co: str) -> pd.Index:
    co_row = df.loc[co_key]
    matched = [col for col in df.columns if target_co in split_co_labels(co_row[col])]
    return pd.Index(matched)


def _is_co_attainment_exempt_column(
    col,
    *,
    normalized_skip_cols: set[str],
    total_cols_in_groups: set,
) -> bool:
    """Columns never shown in Assessment IDs and never warned for missing CO."""
    col_str = str(col)
    normalized_col = normalize_evaluation_name(col_str)
    if normalized_col in normalized_skip_cols:
        return True
    if is_bonus_assessment_column(col_str):
        return True
    if "BEST_TOTAL_" in normalized_col:
        return True
    if col_str in total_cols_in_groups:
        return True
    return False


def _column_has_student_marks(df: pd.DataFrame, col) -> bool:
    """True if any student row has non-zero marks in this column."""
    metadata = {"CO", "MAX_MARKS", "MAX_MARKS_SCALED"}
    candidate_rows = [
        idx for idx in df.index if str(idx).strip().upper() not in metadata
    ]
    if not candidate_rows:
        return False
    series = pd.to_numeric(df.loc[candidate_rows, col], errors="coerce").fillna(0)
    return float(series.sum()) != 0


def _columns_used_in_co_attainment(
    df: pd.DataFrame,
    co_row_key,
    *,
    normalized_skip_cols: set[str],
    total_cols_in_groups: set,
) -> list[str]:
    """Assessment columns that participate in CO attainment (have CO mapping)."""
    used: list[str] = []
    for col in df.columns:
        if _is_co_attainment_exempt_column(
            col, normalized_skip_cols=normalized_skip_cols, total_cols_in_groups=total_cols_in_groups
        ):
            continue
        if co_cell_empty(df.loc[co_row_key, col]):
            continue
        used.append(str(col))
    return used


def _is_missing_co_warning_exempt_column(
    col,
    df: pd.DataFrame,
    *,
    co_row_key,
    max_marks_key,
    normalized_skip_cols: set[str],
    total_cols_in_groups: set,
    col_to_group_key: dict[str, str],
) -> bool:
    """
    Warning-only exemptions. Does not change total_cols_in_groups used elsewhere.
    Group totals (empty CO, in total_cols_in_groups) are exempt only when they have
    the highest Max_Marks among empty-CO columns in the same group — so sub-questions
    like MidSem Q4(a–c) still warn while MidSem Total does not.
    """
    col_str = str(col)
    normalized_col = normalize_evaluation_name(col_str)
    if normalized_col in normalized_skip_cols:
        return True
    if is_bonus_assessment_column(col_str):
        return True
    if "BEST_TOTAL_" in normalized_col:
        return True
    if col_str.endswith(".total") or normalized_col.endswith("TOTAL"):
        return True
    if col_str not in total_cols_in_groups:
        return False
    group_key = col_to_group_key.get(col_str, normalize_group_key(col_str))
    group_empty_co_totals = [
        c
        for c in df.columns
        if col_to_group_key.get(str(c), normalize_group_key(c)) == group_key and c in total_cols_in_groups
    ]
    if not group_empty_co_totals:
        return False
    aggregate_col = max(group_empty_co_totals, key=lambda c: _max_marks_numeric(df, max_marks_key, c))
    return col_str == str(aggregate_col)


def _columns_missing_co_mapping(
    df: pd.DataFrame,
    co_row_key,
    *,
    normalized_skip_cols: set[str],
    total_cols_in_groups: set,
    col_to_group_key: dict[str, str],
    max_marks_key,
) -> list[str]:
    """Scored assessment columns with no CO mapping — faculty should be warned."""
    missing: list[str] = []
    for col in df.columns:
        if _is_missing_co_warning_exempt_column(
            col,
            df,
            co_row_key=co_row_key,
            max_marks_key=max_marks_key,
            normalized_skip_cols=normalized_skip_cols,
            total_cols_in_groups=total_cols_in_groups,
            col_to_group_key=col_to_group_key,
        ):
            continue
        if not co_cell_empty(df.loc[co_row_key, col]):
            continue
        if not _column_has_student_marks(df, col):
            continue
        missing.append(str(col))
    return missing


def _assessment_ids_for_co_attainment(
    df: pd.DataFrame,
    co_attainment_columns: list[str],
    col_to_group_key: dict[str, str],
) -> list[str]:
    """Column labels used in CO attainment (exact names from the marks workbook)."""
    _ = (df, col_to_group_key)
    return list(dict.fromkeys(co_attainment_columns))


def _assessment_type_from_column(column_name: str) -> str:
    token = re.split(r"[_.\s]+", str(column_name).strip())[0]
    return token or str(column_name).strip()


def _assessment_display_name(column_name: str) -> str:
    raw = str(column_name).strip()
    # Collapse common per-question suffixes while preserving faculty-facing labels.
    raw = re.sub(r"_Q\d+$", "", raw, flags=re.IGNORECASE)
    raw = re.sub(r"\.\d+$", "", raw)
    return raw.strip() or str(column_name).strip()


def _build_assessment_co_structure(
    df: pd.DataFrame,
    co_row_key,
    co_attainment_columns: list[str],
    col_to_group_key: dict[str, str],
) -> list[dict]:
    """Per-column CO mappings used for assessment_co_mapping persistence."""
    structure: list[dict] = []
    for col in co_attainment_columns:
        group_key = col_to_group_key.get(str(col), normalize_group_key(str(col)))
        display_name = _assessment_display_name(str(col))
        co_labels = split_co_labels(df.loc[co_row_key, col])
        if not co_labels:
            continue
        for co_label in co_labels:
            structure.append(
                {
                    "name": display_name,
                    "column": str(col),
                    "assessment_type": _assessment_type_from_column(display_name),
                    "co_label": co_label,
                    "question_count": 1,
                }
            )
    return structure


def extract_course_co_po_mapping(mapping_xlsx_path: str, course_pattern: str):
    """
    Returns:
      mapping_df: index = CO1..COn, columns = PO1..PO12, PSO1..PSO3 (numeric weights)
    """
    xl = pd.ExcelFile(mapping_xlsx_path)

    # Prefer the UG mapping sheet (it contains the combined ECE-315/515 line in your file)
    sheet_preference = [
        "Course outcome mapping UG",
        "CO mapping - PG",
        "Course mapping UG",
        "Course mapping PG",
    ]

    for sheet in sheet_preference:
        if sheet not in xl.sheet_names:
            continue

        df = pd.read_excel(mapping_xlsx_path, sheet_name=sheet)
        if df.shape[1] < 16:
            continue

        first_col = df.columns[0]
        col0 = df[first_col]

        # Find the course title row
        hits = [
            i
            for i, v in enumerate(col0.values)
            if isinstance(v, str) and course_title_matches(course_pattern, v)
        ]
        if not hits:
            continue

        start = hits[0]

        # CO rows are immediately below (CO1, CO2, ...)
        co_rows = []
        i = start + 1
        while i < len(df):
            raw = df.loc[i, first_col]
            if pd.isna(raw):
                break
            v = str(raw).strip()
            if v.upper().startswith("CO") and re.match(r"^CO\d+", v, re.IGNORECASE):
                co_rows.append(i)
                i += 1
                continue
            # stop at blank / next course
            if v == "" or re.match(r"^\s*ECE-\d+", v):
                break
            break

        if not co_rows:
            continue

        # In this file layout:
        # col 0 = Course Outcomes, next 12 cols = POs, next 3 cols = PSOs
        po_cols = list(df.columns[1:13])
        pso_cols = list(df.columns[13:16])

        # Row 0 in these cols contains labels like PO1..PO12 and PSO1..PSO3
        po_labels = df.loc[0, po_cols].tolist()
        pso_labels = df.loc[0, pso_cols].tolist()

        mapping = df.loc[co_rows, [first_col] + po_cols + pso_cols].copy()
        mapping = mapping.rename(columns={first_col: "CO"})
        mapping["CO"] = mapping["CO"].astype(str).str.strip()

        rename = {c: l for c, l in zip(po_cols, po_labels)}
        rename.update({c: l for c, l in zip(pso_cols, pso_labels)})
        mapping = mapping.rename(columns=rename).set_index("CO")

        keep = [*po_labels, *pso_labels]  # 12 + 3 = 15

        hml_map = {"H": 3, "h": 3, "High": 3, "M": 2, "m": 2, "Medium": 2, "L": 1, "l": 1, "Low": 1, "": 0}

        mapping = mapping[keep]
        mapping = mapping.apply(lambda col: col.astype(str).str.strip().replace(hml_map).infer_objects(copy=False))

        return mapping

    raise ValueError(f"Could not find course '{course_pattern}' with CO rows in the mapping workbook.")


def extract_course_co_po_mapping_pg(mapping_xlsx_path: str, course_pattern: str):
    """
    PG mapping: index = CO1..COn, columns = PO1..PO4 (numeric weights).
    """
    import logging

    logger = logging.getLogger(__name__)
    xl = pd.ExcelFile(mapping_xlsx_path)
    sheet = "CO mapping - PG"
    if sheet not in xl.sheet_names:
        raise ValueError(f"PG mapping sheet '{sheet}' not found in {mapping_xlsx_path}")

    df = pd.read_excel(mapping_xlsx_path, sheet_name=sheet)
    if df.shape[1] < 5:
        raise ValueError("PG mapping sheet must have at least 5 columns (CO + 4 POs)")

    first_col = df.columns[0]
    col0 = df[first_col]
    hits = [
        i
        for i, v in enumerate(col0.values)
        if isinstance(v, str) and course_title_matches(course_pattern, v)
    ]
    if not hits:
        raise ValueError(f"Could not find course '{course_pattern}' with CO rows in the PG mapping workbook.")

    start = hits[0]
    co_rows: list[int] = []
    i = start + 1
    while i < len(df):
        raw = df.loc[i, first_col]
        if pd.isna(raw):
            break
        v = str(raw).strip()
        if v.upper().startswith("CO") and re.match(r"^CO\d+", v, re.IGNORECASE):
            co_rows.append(i)
            i += 1
            continue
        if v == "" or re.match(r"^\s*ECE-\d+", v):
            break
        break

    if not co_rows:
        raise ValueError(f"Could not find CO rows for course '{course_pattern}' in the PG mapping workbook.")

    po_cols = list(df.columns[1:5])
    po_labels = df.loc[0, po_cols].tolist()

    mapping = df.loc[co_rows, [first_col] + po_cols].copy()
    mapping = mapping.rename(columns={first_col: "CO"})
    mapping["CO"] = mapping["CO"].astype(str).str.strip()

    rename = {c: l for c, l in zip(po_cols, po_labels)}
    mapping = mapping.rename(columns=rename).set_index("CO")

    hml_map = {"H": 3, "h": 3, "High": 3, "M": 2, "m": 2, "Medium": 2, "L": 1, "l": 1, "Low": 1, "": 0}
    mapping = mapping[po_labels]
    mapping = mapping.apply(lambda col: col.astype(str).str.strip().replace(hml_map).infer_objects(copy=False))

    for co in mapping.index:
        if str(co).strip() and str(co).upper().startswith("CO") and co not in mapping.index:
            logger.warning("CO %s not found in PG mapping file — skipped", co)

    return mapping


def compute_po_pso_weighted_avg(co_prime_percent: pd.Series, mapping_df: pd.DataFrame):
    """
    co_prime_percent: Series like {CO1: 72.3, CO2: 81.0, ...} in 0..100 scale
    mapping_df: index COi, columns PO1..PO12, PSO1..PSO3 with weights (1/2/3)

    Returns: Series indexed by PO/PSO with weighted-average (0..100 scale)
    """
    cp = co_prime_percent.copy()
    cp.index = cp.index.astype(str).str.strip()

    common = cp.index.intersection(mapping_df.index)
    if len(common) == 0:
        raise ValueError("No overlap between CO' names and mapping CO names.")

    cp = cp.loc[common].astype(float)
    W = mapping_df.loc[common].astype(float)

    numerator = (W.mul(cp, axis=0)).sum(axis=0)
    denom = W.sum(axis=0).replace(0, np.nan)

    return numerator / denom

def main_process(
    course_file_path,
    mapping_file_path,
    course_title,
    included_rolls=None,
    target_value=50,
    mapping_type: str = "UG",
):
    """
    Main processing function for CO-PO analysis
    
    Args:
        course_file_path: Path to the course data Excel file
        mapping_file_path: Path to the CO-PO mapping Excel file
        course_title: Title/pattern of the course to search in mapping file
        included_rolls: Optional list of roll numbers to include. If None, excludes MT/PhD by default.
        target_value: Target value for CO attainment threshold (default: 50). Range: 0-100.
    
    Returns:
        dict: Contains results including excel_path, statistics, and dataframes
    """
    # Step 3: File path configuration
    source = course_file_path
    destination = source.replace('.xlsx', '_CO_Percentage_Results.xlsx')

    # # Step 4: Read data
    # df = pd.read_csv(source, header=0, index_col=0)
    # original_data = df.copy()
    # Step 4: Read Excel data
    df = pd.read_excel(source, header=0, index_col=0)

    # Drop fully empty student rows, but keep CO / Max_Marks metadata even when blank
    _metadata_row_labels = {
        'CO', 'CO TO BE ENTERED', 'MAX_MARKS', 'MAX MARKS', 'MARKS', 'MAX_MARKS_SCALED',
    }
    empty_rows = [
        idx for idx in df.index
        if str(idx).strip().upper() not in _metadata_row_labels and df.loc[idx].isna().all()
    ]
    if empty_rows:
        df.drop(index=empty_rows, inplace=True)

    # --- Pre-processing: normalize structure ---

    # 1. Strip whitespace from index (fixes " MT24166" -> "MT24166")
    df.index = df.index.map(lambda x: str(x).strip() if isinstance(x, str) else x)

    # 2. Strip whitespace from column names
    df.columns = df.columns.map(lambda x: str(x).strip() if isinstance(x, str) else x)

    # 3. Drop "Unnamed:" columns (typically metadata like Branch, Student Name)
    unnamed_cols = [c for c in df.columns if str(c).startswith('Unnamed')]
    if unnamed_cols:
        print(f"Dropping unnamed metadata columns: {unnamed_cols}")
        df.drop(columns=unnamed_cols, inplace=True)

    # 3b. Normalize metadata row aliases (CO to be entered, Marks, Max Marks)
    index_alias_map = {}
    for idx in df.index:
        label = str(idx).strip().upper()
        if label == 'CO TO BE ENTERED':
            index_alias_map[idx] = 'CO'
        elif label in ('MARKS', 'MAX MARKS'):
            index_alias_map[idx] = 'Max_Marks'
    if index_alias_map:
        df.rename(index=index_alias_map, inplace=True)
        print(f"Renamed metadata rows: {index_alias_map}")

    # 4. Accept Max_Marks_scaled as alias for Max_Marks (case-insensitive)
    index_upper_map = {str(idx).strip().upper(): idx for idx in df.index}
    max_marks_key = None
    for k in index_upper_map:
        if k == 'MAX_MARKS':
            max_marks_key = index_upper_map[k]
            break
    max_marks_scaled_key = None
    for k in index_upper_map:
        if k == 'MAX_MARKS_SCALED':
            max_marks_scaled_key = index_upper_map[k]
            break
    if max_marks_scaled_key and not max_marks_key:
        df.rename(index={max_marks_scaled_key: 'Max_Marks'}, inplace=True)
        print(f"Renamed row '{max_marks_scaled_key}' -> 'Max_Marks'")
        max_marks_key = 'Max_Marks'

    # Always use the actual key for Max_Marks (case-insensitive)
    def get_max_marks_key():
        for k in df.index:
            if str(k).strip().upper() == 'MAX_MARKS':
                return k
        return None

    # 5. Drop known non-data metadata rows (e.g. "Roll No." with Q1/Q2/Total labels, or NaN index)
    meta_rows_to_drop = [idx for idx in df.index
                         if pd.isna(idx) or str(idx).strip() in ('Roll No.', 'Roll No')]
    if meta_rows_to_drop:
        df.drop(index=meta_rows_to_drop, inplace=True)
        print(f"Dropped metadata rows: {meta_rows_to_drop}")

    original_data = df.copy()

    # Normalize Result / Grade_Point column aliases (e.g. Result.1, Grade, Final grade)
    def _grade_column_alias(col_name: str) -> str | None:
        norm = normalize_evaluation_name(col_name)
        if norm in ("GRADEPOINT", "GRADE_POINT", "GRADE", "FINALGRADE", "FINAL_GRADE"):
            return "Grade_Point"
        if norm.startswith("GRADEPOINT."):
            return "Grade_Point"
        return None

    for col in list(df.columns):
        norm = normalize_evaluation_name(col)
        if norm.startswith("RESULT") and "Result" not in df.columns:
            df.rename(columns={col: "Result"}, inplace=True)
            continue
        grade_alias = _grade_column_alias(col)
        if grade_alias and grade_alias not in df.columns:
            df.rename(columns={col: grade_alias}, inplace=True)

    if "Grade_Point" not in df.columns:
        grade_candidates = [
            c for c in df.columns
            if normalize_evaluation_name(c).startswith("GRADEPOINT")
            or normalize_evaluation_name(c) in ("GRADE", "FINALGRADE")
        ]
        if grade_candidates:
            def _has_letter_grades(column_name: str) -> bool:
                sample = df[column_name].dropna().astype(str).head(30)
                return any(re.match(r"^[A-F][+-]?$", v.strip().upper()) for v in sample)

            preferred = next((c for c in grade_candidates if _has_letter_grades(c)), grade_candidates[-1])
            df.rename(columns={preferred: "Grade_Point"}, inplace=True)

    # --- Validate required structure ---
    errors = []
    co_warnings: list[str] = []

    # Check required row labels in the index (case-insensitive)
    required_rows = {'CO': 'CO (Course Outcome mapping per assessment)',
                     'Max_Marks': 'Max_Marks (maximum marks per assessment)'}
    # Normalize index labels to uppercase for case-insensitive check
    index_upper = {str(idx).strip().upper() for idx in df.index}
    for row_label, description in required_rows.items():
        if row_label.upper() not in index_upper:
            errors.append(f'Missing required row "{row_label}" — expected a row labelled "{row_label}" for {description}.')

    # Check required columns
    required_cols = {'Result': 'Result (total marks obtained by each student)',
                     'Grade_Point': 'Grade_Point (letter grade for each student, e.g. A+, B, C-)'}
    for col_name, description in required_cols.items():
        if col_name not in df.columns:
            errors.append(f'Missing required column "{col_name}" — expected a column for {description}.')

    # --- Build assessment groups & detect total columns by CO content ---
    skip_cols = {'Result', 'Grade_Point', 'Bonus', 'Numeric_Grade_Point', 'Branch'}
    all_cols_set = set(df.columns)
    normalized_skip_cols = {normalize_evaluation_name(col) for col in skip_cols}

    # Group columns: parent -> [all columns in the group (parent + parent.1, parent.2, ...)]
    assessment_groups = {}  # normalized_parent_name -> list of column names
    for col in df.columns:
        if normalize_evaluation_name(col) in normalized_skip_cols:
            continue
        col_str = str(col)
        m = re.match(r'^(.+)\.(\d+)$', col_str)
        if m:
            parent = m.group(1).strip()
            parent_key = normalize_group_key(parent)
            if parent_key not in assessment_groups:
                assessment_groups[parent_key] = []
            assessment_groups[parent_key].append(col)

    # Add un-suffixed parent columns to their group
    for col in df.columns:
        col_key = normalize_group_key(col)
        if col_key in assessment_groups and normalize_evaluation_name(col) not in normalized_skip_cols:
            if col not in assessment_groups[col_key]:
                assessment_groups[col_key].insert(0, col)

    # Also detect case/space variants that belong to the same group.
    cols_in_groups = set()
    for cols in assessment_groups.values():
        cols_in_groups.update(cols)
    for col in df.columns:
        if col in cols_in_groups or normalize_evaluation_name(col) in normalized_skip_cols:
            continue
        col_key = normalize_group_key(col)
        for parent_key in assessment_groups:
            if col_key == parent_key:
                assessment_groups[parent_key].append(col)
                cols_in_groups.add(col)
                print(f"Added '{col}' to group '{parent_key}' (case/space-normalized match)")
                break

    # Attach typo variants (especially unsuffixed totals) to the closest parent group.
    for col in df.columns:
        if col in cols_in_groups or normalize_evaluation_name(col) in normalized_skip_cols:
            continue
        col_key = normalize_group_key(col)
        col_prefix, col_num = _group_name_parts(col_key)
        best_key = None
        best_score = 0.0
        for parent_key in assessment_groups:
            parent_prefix, parent_num = _group_name_parts(parent_key)
            if col_num and parent_num and col_num != parent_num:
                continue
            if col_prefix and parent_prefix and col_prefix[:2] != parent_prefix[:2]:
                continue
            score = SequenceMatcher(None, col_key, parent_key).ratio()
            if score > best_score:
                best_score = score
                best_key = parent_key
        if best_key and best_score >= 0.82:
            assessment_groups[best_key].append(col)
            cols_in_groups.add(col)
            print(f"Added '{col}' to group '{best_key}' (typo-tolerant match)")

    # Merge near-identical groups (e.g., typo variants like ASSIGN1/ASSING1).
    group_keys = list(assessment_groups.keys())
    for i, left in enumerate(group_keys):
        if left not in assessment_groups:
            continue
        for right in group_keys[i + 1:]:
            if right not in assessment_groups:
                continue
            left_prefix, left_num = _group_name_parts(left)
            right_prefix, right_num = _group_name_parts(right)
            if left_num and right_num and left_num != right_num:
                continue
            if left_prefix and right_prefix and left_prefix[:2] != right_prefix[:2]:
                continue
            similarity = SequenceMatcher(None, left, right).ratio()
            if similarity >= 0.82:
                assessment_groups[left].extend(assessment_groups[right])
                assessment_groups[left] = list(dict.fromkeys(assessment_groups[left]))
                del assessment_groups[right]

    col_to_group_key: dict[str, str] = {}
    for gkey, cols in assessment_groups.items():
        for c in cols:
            col_to_group_key[str(c)] = gkey

    # For each group, identify total columns (those with NaN CO) — position doesn't matter
    total_cols_in_groups = set()
    if 'CO' in df.index:
        for parent_key, cols in assessment_groups.items():
            group_totals = []
            for col in cols:
                co_val = df.loc['CO', col]
                normalized_col = normalize_evaluation_name(col)
                if co_cell_empty(co_val) or "BEST_TOTAL_" in normalized_col:
                    group_totals.append(col)
                    total_cols_in_groups.add(col)
            if not group_totals:
                scored_with_co = [
                    str(c)
                    for c in cols
                    if normalize_evaluation_name(c) not in normalized_skip_cols
                    and not co_cell_empty(df.loc["CO", c])
                ]
                scored_cols = [
                    str(c)
                    for c in cols
                    if normalize_evaluation_name(c) not in normalized_skip_cols
                ]
                # Single scored column or every sub-question has its own CO — no separate total needed.
                if len(scored_with_co) == 1 or (
                    scored_cols and len(scored_with_co) == len(scored_cols)
                ):
                    continue
                errors.append(
                    f'No total column found for assessment group "{parent_key}" '
                    f'(columns: {", ".join(str(c) for c in cols)}). '
                    f'One column in each group should have an empty CO row (the total column).'
                )

    co_row_key_for_checks = get_co_row_key(df) if "CO" in df.index else None
    cols_missing_co: list[str] = []
    co_attainment_columns: list[str] = []
    max_marks_key_for_checks = get_max_marks_row_key(df)
    if co_row_key_for_checks is not None:
        cols_missing_co = _columns_missing_co_mapping(
            df,
            co_row_key_for_checks,
            normalized_skip_cols=normalized_skip_cols,
            total_cols_in_groups=total_cols_in_groups,
            col_to_group_key=col_to_group_key,
            max_marks_key=max_marks_key_for_checks,
        )
        co_attainment_columns = _columns_used_in_co_attainment(
            df,
            co_row_key_for_checks,
            normalized_skip_cols=normalized_skip_cols,
            total_cols_in_groups=total_cols_in_groups,
        )

    if cols_missing_co:
        co_warnings.append(
            "The following component(s) or question column(s) have no CO mapping and were "
            f"excluded from CO attainment: {', '.join(cols_missing_co)}."
        )

    # Validate that CO row has at least some CO values
    if 'CO' in df.index:
        co_values_check = df.loc['CO'].dropna().astype(str)
        co_pattern_found = any(re.search(r'CO\d+', v) for v in co_values_check)
        if not co_pattern_found:
            errors.append(
                'The "CO" row exists but does not contain any valid CO labels (e.g. CO1, CO2, ...). '
                'Ensure the CO row maps each assessment to its course outcome(s).'
            )

    # Raise all collected errors at once
    if errors:
        raise ValueError(
            'The uploaded course data file has structural issues:\n• ' + '\n• '.join(errors) +
            '\n\nExpected columns: [...assessment columns...], Result, Grade_Point' +
            '\nExpected rows (index): CO, Max_Marks, followed by student roll numbers.' +
            '\nEach assessment group needs a total column alongside its sub-part columns.'
        )

    # --- Normalize CO row: strip spaces around commas and each CO label ---
    for column in df.columns:
        co_val = df.loc['CO', column]
        if isinstance(co_val, str):
            # Normalize: "CO1, CO2 , CO3" -> "CO1,CO2,CO3" and " CO2" -> "CO2"
            normalized = ','.join(part.strip() for part in co_val.split(','))
            df.loc['CO', column] = normalized

    for column in df.columns:
        if type(df.loc['CO', column]) == str:
            df.rename(columns={column: column.strip()}, inplace=True)

    # --- Normalize Grade_Point column: strip spaces, fix formats like "A -", "A +", " B" ---
    # Also infer letter grades from numeric values (10->A+, 9->A-, 8->B, etc.)
    if 'Grade_Point' in df.columns:
        # Reverse mapping: numeric value -> letter grade
        numeric_to_grade = {
            10: 'A+', 9: 'A-', 8: 'B', 7: 'B-', 6: 'C', 5: 'C-', 4: 'D', 2: 'F', 0: 'I'
        }
        def normalize_grade(val):
            # If already a number (int/float), try to infer the letter grade
            if isinstance(val, (int, float)):
                if pd.isna(val):
                    return val
                int_val = int(val)
                if int_val in numeric_to_grade:
                    return numeric_to_grade[int_val]
                return val  # keep as-is if not in mapping
            if not isinstance(val, str):
                return val
            # Remove all spaces: "A -" -> "A-", "A +" -> "A+", " B  " -> "B"
            cleaned = val.replace(' ', '').upper()
            # If it's a numeric string like "10", "9", etc., infer the grade
            try:
                num = int(cleaned)
                if num in numeric_to_grade:
                    return numeric_to_grade[num]
                return val
            except ValueError:
                pass
            return cleaned
        df['Grade_Point'] = df['Grade_Point'].apply(normalize_grade)

    assessment_ids_display = _assessment_ids_for_co_attainment(
        df, co_attainment_columns, col_to_group_key
    )
    assessment_co_structure = []
    if co_row_key_for_checks is not None and co_attainment_columns:
        assessment_co_structure = _build_assessment_co_structure(
            df,
            co_row_key_for_checks,
            co_attainment_columns,
            col_to_group_key,
        )
    print("CO attainment columns:", co_attainment_columns)
    print("Canonical Assessment IDs:", assessment_ids_display)

    assessment_ids = df.columns.drop(["Grade_Point"], errors="ignore")

    # Step 6: Extract unique COs (CO1, CO2, … only)
    co_row_key = get_co_row_key(df)
    if co_row_key is None:
        raise ValueError('Missing required row "CO" in the data file.')
    unique_COs: list[str] = []
    seen_cos: set[str] = set()
    for val in df.loc[co_row_key]:
        for label in split_co_labels(val):
            if label not in seen_cos:
                seen_cos.add(label)
                unique_COs.append(label)
    unique_COs.sort(key=lambda x: int(re.findall(r"\d+", x)[0]))

    print('Unique COs:', unique_COs)

    metadata_labels = {'CO', 'Max_Marks'}
    all_students = [idx for idx in df.index
                    if not pd.isna(idx) and str(idx).strip() not in metadata_labels]
    # Filter students based on included_rolls selection or default exclusion
    if included_rolls is not None:
        included_set = set(str(r).strip() for r in included_rolls)
        students = [s for s in all_students if str(s).strip() in included_set]
        filter_label = "Selected"
    else:
        # Default: exclude MT and PhD roll numbers from all computations
        students = [s for s in all_students if not str(s).upper().startswith("MT") and not str(s).upper().startswith("PHD")]
        filter_label = "Non-MT/PhD"
    print(f"Filtered students: {len(students)} kept out of {len(all_students)} ({filter_label})")

    # Step 7: Handle best assessments
    best_total_COs = []
    select_no_assessments = []
    total_no_assessments = []
    best_select_from_assessments_list = []

    for assessment_id in assessment_ids:
        normalized_assessment_id = normalize_evaluation_name(assessment_id)
        if 'BEST_TOTAL_' in normalized_assessment_id:
            select_no_assessments.append(int(normalized_assessment_id.split('BEST_TOTAL_')[1][0]))
            total_no_assessments.append(int(normalized_assessment_id.split('BEST_TOTAL_')[-1][-1]))
            co_cell = df.loc[co_row_key, assessment_id]
            co_list = split_co_labels(co_cell)

            best_total_COs.append(co_list)
            best_select_from_assessments_list.append([co for co in unique_COs if co in best_total_COs[-1]])
            unique_COs = [co for co in unique_COs if co not in best_total_COs[-1]]

    print('Best Total COs:', best_total_COs)
    print('Assessment IDs:', assessment_ids)
    print('COs:', unique_COs)
    print('Students:', students)

    # Step 8: Get_Worst Function
    def Get_Worst(student_row, list_assessment=best_select_from_assessments_list, no_select_assessment=select_no_assessments, no_total_from_assessment=total_no_assessments):
        not_to_include_assessments = []
        normalized_keys = {key: normalize_evaluation_name(key) for key in student_row.keys()}

        for i in range(len(list_assessment)):
            assessment_scores = {}
            for assessment in list_assessment[i]:
                score = 0.0
                for key in student_row.keys():
                    if normalized_keys[key].startswith(normalize_evaluation_name(assessment)):
                        score += float(student_row[key])
                assessment_scores[assessment] = score

            sorted_assessments = sorted(assessment_scores.items(), key=lambda item: item[1], reverse=True)
            selected_assessments = sorted_assessments[:no_select_assessment[i]]
            not_to_include_assessments.append([assessment[0] for assessment in sorted_assessments[no_select_assessment[i]:]])
            not_to_include_assessments[i] = ', '.join(not_to_include_assessments[i])

        not_to_include_assessments = [x for x in not_to_include_assessments if x.strip()]

        return not_to_include_assessments

    # Step 9: Prepare empty DataFrame (AUTOMATIC)
    # unique_COs is created in Step 6

    # keep only CO-like entries, e.g., CO1, CO2, ... (extra safety)
    un = [c for c in unique_COs if re.fullmatch(r"CO\d+", str(c).strip())]

    # sort numerically: CO1, CO2, ..., CO10 (not CO1, CO10, CO2)
    un = sorted(un, key=lambda x: int(re.findall(r"\d+", x)[0]))

    CO_percentage_df = pd.DataFrame(columns=un)

    print("Detected CO columns:", un)

    # Step 10: Grade mapping (grades already normalized in earlier step)
    grade_mapping = {
        'A+': 10, 'A': 10, 'A-': 9, 'B': 8, 'B-': 7, 'B+': 8,
        'C': 6, 'C-': 5, 'C+': 6, 'D': 4, 'F': 2, 'W': 0, 'I': 0
    }
    def map_grade(val):
        # If already numeric, use directly
        if isinstance(val, (int, float)):
            return val
        # Try letter-grade mapping
        mapped = grade_mapping.get(val)
        if mapped is not None:
            return mapped
        # Try parsing as number (e.g. "9")
        try:
            return float(val)
        except (ValueError, TypeError):
            return val
    df['Numeric_Grade_Point'] = df['Grade_Point'].apply(map_grade)

    # Step 11: CO Calculation Loop
    for roll_no in students:
        if best_total_COs:
            avoid_assessment = Get_Worst(student_row=df.loc[roll_no])

        CO_dict = {}

        for CO in un:
            CO_dict[CO] = 0
            assessments_with_current_CO = columns_mapped_to_co(df, co_row_key, CO)

            assessments_with_current_CO = assessments_with_current_CO[~assessments_with_current_CO.str.contains('Roll No|CO|Grade_Point')]

            if best_total_COs:
                if best_total_COs:
                    assessments_with_current_CO_new = [
                        assessment for assessment in assessments_with_current_CO
                        if not any(
                            normalize_evaluation_name(assessment).startswith(normalize_evaluation_name(avoid))
                            for avoid in avoid_assessment
                        )
                    ]
                assessments_with_current_CO = pd.Index(assessments_with_current_CO_new)

            bonus_with_current_CO = 0.0
            if 'Bonus' in assessments_with_current_CO:
                bonus_with_current_CO = pd.to_numeric(
                    pd.Series([df.loc[roll_no, 'Bonus']]), errors='coerce'
                ).fillna(0.0).iloc[0]
                assessments_with_current_CO = assessments_with_current_CO.drop('Bonus')

            student_marks = pd.to_numeric(
                df.loc[roll_no, assessments_with_current_CO], errors='coerce'
            ).fillna(0.0)
            sum_student_marks = float(student_marks.sum()) + bonus_with_current_CO

            max_marks_row_key = get_max_marks_key()
            if max_marks_row_key is None:
                raise ValueError('Max_Marks row not found (case-insensitive) in the data file.')
            max_marks = pd.to_numeric(
                df.loc[max_marks_row_key, assessments_with_current_CO], errors='coerce'
            ).fillna(0.0)
            sum_max_marks = float(max_marks.sum())

            student_result = pd.to_numeric(
                pd.Series([df.loc[roll_no, 'Result']]), errors='coerce'
            ).fillna(0.0).iloc[0]
            student_result = 1 if student_result == 0 else student_result

            grade_point = df.loc[roll_no, 'Numeric_Grade_Point']
            try:
                grade_point = float(grade_point)
            except:
                grade_point = 0

            sum_max_marks = 1 if sum_max_marks == 0 else sum_max_marks

            CO_percentage = min(100, ((sum_student_marks / student_result) * (100 / sum_max_marks) * (grade_point * 10)))

            CO_dict[CO] = CO_percentage

        CO_percentage_df.loc[roll_no] = CO_dict

    # Step 12: Save result
    CO_percentage_df = CO_percentage_df.astype(float)
    final_df = pd.concat([original_data, CO_percentage_df], axis=1)

    # Remove MT and PhD roll numbers from final output
    metadata_rows = [idx for idx in df.index if str(idx).strip().upper() in {'CO', 'MAX_MARKS'}]
    keep_indices = metadata_rows + students  # metadata + filtered students only
    final_df = final_df.loc[final_df.index.isin(keep_indices)]

    # Update destination file path to Excel format
    destination = destination.replace('.csv', '.xlsx')

    # Save to Excel
    final_df.to_excel(destination, index=True)

    # co_cols = ["CO1", "CO2", "CO3"]
    co_cols = [c for c in CO_percentage_df.columns if re.fullmatch(r"CO\d+", str(c))]
    co_cols = sorted(co_cols, key=lambda x: int(re.findall(r"\d+", x)[0]))

    # --- CO values used for stats (MT/PhD already excluded from students list) ---
    co_values = (
        CO_percentage_df[co_cols]
        .apply(pd.to_numeric, errors="coerce")
    )

    # Denominator per CO: number of NON-MT students with a valid numeric score in that CO
    denom = co_values.notna().sum()

    mean_vals = co_values.mean()
    std_vals  = co_values.std(ddof=1)              # sample std
    thr_vals  = np.maximum(target_value, mean_vals - 0.5 * std_vals)

    # Numerator per CO: number of NON-MT students with score > threshold (and not NaN)
    num_above = (co_values.gt(thr_vals)).sum()

    # Percentage per CO
    pct_above = (num_above / denom.replace(0, np.nan)) * 100.0

    # --- Make labels appear just before CO1 in the OUTPUT sheet ---
    out_df = final_df.copy()

    # Move index to a normal column so Excel doesn't get an extra "first column" for index
    if out_df.index.name is not None or not isinstance(out_df.index, pd.RangeIndex):
        out_df = out_df.reset_index()
        if "index" in out_df.columns:
            out_df = out_df.rename(columns={"index": "Roll No"})

    if "CO1" not in out_df.columns:
        raise ValueError("CO1 not found in output dataframe. Ensure CO1/CO2/CO3 were appended first.")

    co1_pos = list(out_df.columns).index("CO1")
    label_col = out_df.columns[co1_pos - 1] if co1_pos > 0 else out_df.columns[0]

    labels = [
        "",  # blank separator row
        "Mean",
        "Std Dev",
        "Mean - 0.5*Std",
        f"% > max({target_value},Mean - 0.5*Std) [{filter_label}]"
    ]

    summary_df = pd.DataFrame(np.nan, index=range(len(labels)), columns=out_df.columns)
    if label_col in summary_df.columns:
        summary_df[label_col] = summary_df[label_col].astype(object)

    for i, lab in enumerate(labels):
        summary_df.loc[i, label_col] = lab if lab else np.nan

    summary_df.loc[1, co_cols] = mean_vals.values
    summary_df.loc[2, co_cols] = std_vals.values
    summary_df.loc[3, co_cols] = thr_vals.values
    summary_df.loc[4, co_cols] = pct_above.values   # percentage numbers (0–100)

    # Append at bottom
    out_df = pd.concat([out_df, summary_df], axis=0, ignore_index=True)

    # Save without index column
    out_df.to_excel(destination, index=False)

    print("Saved with CO stats + percentage above threshold (MT/PhD excluded) to:", destination)

    # Extract CO-PO mapping and compute PO/PSO attainment
    import logging

    logger = logging.getLogger(__name__)
    if str(mapping_type).upper() == "PG":
        mapping_df = extract_course_co_po_mapping_pg(mapping_file_path, course_title)
    else:
        mapping_df = extract_course_co_po_mapping(mapping_file_path, course_title)

    overlap_cos = [co for co in unique_COs if co in mapping_df.index]
    for co in unique_COs:
        if co not in mapping_df.index:
            logger.warning("CO %s not found in mapping file — skipped", co)
    if not overlap_cos:
        raise ValueError("No CO labels from the marks file were found in the selected mapping file.")
    po_pso_attainment = compute_po_pso_weighted_avg(pct_above.loc[overlap_cos], mapping_df)

    print(po_pso_attainment)

    label_col = "CO Stats"
    if label_col not in out_df.columns:
        if "CO1" in out_df.columns:
            out_df.insert(list(out_df.columns).index("CO1"), label_col, "")
        else:
            out_df[label_col] = ""

    po_pso_cols = list(po_pso_attainment.index)  # PO1..PO12, PSO1..PSO3

    # Ensure PO/PSO columns exist so Excel can show values
    for c in po_pso_cols:
        if c not in out_df.columns:
            out_df[c] = np.nan

    # Optional: keep PO/PSO columns together at end
    base_cols = [c for c in out_df.columns if c not in po_pso_cols]
    out_df = out_df[base_cols + po_pso_cols]

    def empty_row():
        return {c: np.nan for c in out_df.columns}

    blank = empty_row()

    # ---- Placeholder rows (NO values; to be filled later) ----
    indirect_avg = empty_row()
    indirect_avg[label_col] = "Indirect CO avg"

    indirect_avg_5 = empty_row()
    indirect_avg_5[label_col] = "Indirect CO avg scaled by 5"

    # ---- Local PO/PSO heading row near bottom ----
    header = empty_row()
    header[label_col] = "PO/PSO"
    for c in po_pso_cols:
        header[c] = c

    # ---- Values row (FILLED) ----
    values = empty_row()
    values[label_col] = f"Weighted Avg using CO'  (% > max({target_value},Mean-0.5*Std))  [{filter_label}]"
    for k, v in po_pso_attainment.items():
        values[k] = float(v)

    append_block = pd.DataFrame(
        [blank, indirect_avg, indirect_avg_5, header, values],
        columns=out_df.columns
    )

    out_df = pd.concat([out_df, append_block], axis=0)

    # ---- Append CO↔PO/PSO mapping table for verification (from mapping_df) ----
    co_in_map = [c for c in co_cols if c in mapping_df.index]
    if len(co_in_map) == 0:
        raise ValueError("No COs from this course found in mapping_df to print mapping table.")

    map_for_print = mapping_df.loc[co_in_map, po_pso_cols].copy()

    blank2 = empty_row()

    map_title = empty_row()
    map_title[label_col] = "CO↔PO/PSO Mapping (from mapping sheet)"

    map_header = empty_row()
    map_header[label_col] = "CO"
    for c in po_pso_cols:
        map_header[c] = c

    map_rows = []
    for co in map_for_print.index:
        r = empty_row()
        r[label_col] = co
        for c in po_pso_cols:
            r[c] = map_for_print.loc[co, c]
        map_rows.append(r)

    mapping_block = pd.DataFrame([blank2, map_title, map_header] + map_rows, columns=out_df.columns)

    out_df = pd.concat([out_df, mapping_block], axis=0)

    out_df.to_excel(destination, index=False)

    print("Saved with PO/PSO values restored under local headings to:", destination)
    
    # Convert mapping_df to dict of dicts for template
    CO_PO_mapping = {}
    for co in mapping_df.index:
        CO_PO_mapping[co] = {po: float(mapping_df.loc[co, po]) for po in mapping_df.columns}
    
    # Prepare return data to match template expectations
    results = {
        'excel_path': destination,
        'unique_COs': un,  # List of unique COs
        'assessment_ids': assessment_ids_display,  # Canonical evaluation labels for dashboard display
        'assessment_co_structure': assessment_co_structure,
        'CO_stats': {  # Capital letters to match template
            'mean': mean_vals.to_dict(),
            'std': std_vals.to_dict(),
            'threshold': thr_vals.to_dict(),
            'pct_above': pct_above.to_dict()
        },
        'CO_PO_mapping': CO_PO_mapping,  # Dict of dicts for template
        'po_pso_attainment': po_pso_attainment.to_dict(),
        'co_warnings': co_warnings,
    }
    
    return results


if __name__ == "__main__":
    # Example usage when run as standalone script
    filename = 'F&W_edited (1).xlsx'
    folder_path = ''
    source = os.path.join(folder_path, filename)
    mapping_path = 'Course, CO and PO mapping Nov 2025 (2).xlsx'
    course_pattern = "ECE-230: Fields and Waves (F&W)"
    
    results = main_process(source, mapping_path, course_pattern)
    print("Processing complete!")
