"""Add budget module tables."""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "033_budget_module"
down_revision: Union[str, None] = "032_document_chunk_embeddings"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(table: str) -> bool:
    return inspect(op.get_bind()).has_table(table)


def upgrade() -> None:
    if not _has_table("budget_income"):
        op.create_table(
            "budget_income",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("date", sa.String(length=32), nullable=True),
            sa.Column("financial_year", sa.String(length=32), nullable=True),
            sa.Column("budget_head", sa.Text(), nullable=False),
            sa.Column("amount_text", sa.String(length=255), nullable=True),
            sa.Column("amount", sa.Float(), nullable=False, server_default="0"),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("utilised_amount_lakh", sa.Float(), nullable=False, server_default="0"),
            sa.Column("purchases_for", sa.Text(), nullable=True),
            sa.Column("invoice", sa.String(length=512), nullable=True),
            sa.Column("invoice_url", sa.String(length=1024), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_budget_income_financial_year", "budget_income", ["financial_year"])

        income = sa.table(
            "budget_income",
            sa.column("id", sa.Integer),
            sa.column("financial_year", sa.String),
            sa.column("budget_head", sa.Text),
            sa.column("amount_text", sa.String),
            sa.column("amount", sa.Float),
            sa.column("description", sa.Text),
            sa.column("utilised_amount_lakh", sa.Float),
            sa.column("purchases_for", sa.Text),
            sa.column("invoice", sa.String),
            sa.column("invoice_url", sa.String),
        )
        op.bulk_insert(
            income,
            [
                {
                    "id": 1,
                    "financial_year": "2026-2027",
                    "budget_head": "End-to-End Testbed on Beyond 5G",
                    "amount_text": "Rs. 50 Lakhs",
                    "amount": 5000000,
                    "description": "Hardware for Beyond 5G, including NTN, SDRs, UAVs, and underwater communication setups.",
                    "utilised_amount_lakh": 5.07933,
                    "purchases_for": "",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 2,
                    "financial_year": "2026-2027",
                    "budget_head": "Dedicated Servers for ECE Department",
                    "amount_text": "Rs. 5 Crores",
                    "amount": 50000000,
                    "description": "DGX-like and CPU servers for high computational power needs in research.",
                    "utilised_amount_lakh": 0.59205,
                    "purchases_for": "3.8 Cr, (Dr. Saket)",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 3,
                    "financial_year": "2026-2027",
                    "budget_head": "Distinguished Guests",
                    "amount_text": "Rs. 10 Lakhs/year for 2 years (Total 20 lakhs)",
                    "amount": 2000000,
                    "description": "Engage international faculty for mentoring and collaborative grant writing.",
                    "utilised_amount_lakh": 0,
                    "purchases_for": "",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 4,
                    "financial_year": "2026-2027",
                    "budget_head": "ECE Floor Transformation",
                    "amount_text": "Rs. 3 Lakhs",
                    "amount": 300000,
                    "description": "Enhance floor with lab pictures, screens, and video demos.",
                    "utilised_amount_lakh": 0,
                    "purchases_for": "",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 5,
                    "financial_year": "2026-2027",
                    "budget_head": "Hosting Conferences",
                    "amount_text": "Rs. 2 Lakhs/year for 2 years (Total 4 lakhs)",
                    "amount": 400000,
                    "description": "Hosting academic conferences to improve research visibility.",
                    "utilised_amount_lakh": 0,
                    "purchases_for": "",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 6,
                    "financial_year": "2026-2027",
                    "budget_head": "Scholarship for Top Performers",
                    "amount_text": "Rs. 12 Lakhs for 2 years",
                    "amount": 1200000,
                    "description": "Retain high-performing students through scholarships.",
                    "utilised_amount_lakh": 1.51612,
                    "purchases_for": "",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 7,
                    "financial_year": "2026-2027",
                    "budget_head": "Inviting School Students",
                    "amount_text": "Rs. 2.5 Lakhs for 2 years",
                    "amount": 250000,
                    "description": "Training modules and challenges for school students to attract bright minds.",
                    "utilised_amount_lakh": 0,
                    "purchases_for": "",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 8,
                    "financial_year": "2026-2027",
                    "budget_head": "Industry-Academia Ideathons",
                    "amount_text": "Rs. 15 Lakhs/year for 2 years (Total 30 lakhs)",
                    "amount": 3000000,
                    "description": "Ideathons to connect industry with academia and improve UG student perception.",
                    "utilised_amount_lakh": 10.05,
                    "purchases_for": "Events of CiPD with ECE; 1.5 for Telecom Shakti",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 9,
                    "financial_year": "2026-2027",
                    "budget_head": "Digital Whiteboards for Faculty",
                    "amount_text": "Rs. 10 Lakhs",
                    "amount": 1000000,
                    "description": "Equip offices with digital whiteboards for enhanced discussions and screen-sharing, air-purifiers.",
                    "utilised_amount_lakh": 3.9,
                    "purchases_for": "Panel & Camera",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 10,
                    "financial_year": "2026-2027",
                    "budget_head": "Embedded Systems Equipment",
                    "amount_text": "Rs. 29 Lakhs",
                    "amount": 2900000,
                    "description": "Advanced embedded system boards for teaching and research.",
                    "utilised_amount_lakh": 1.28634,
                    "purchases_for": "",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
                {
                    "id": 11,
                    "financial_year": "2026-2027",
                    "budget_head": "Nanofabrication Consumables",
                    "amount_text": "Rs. 15 Lakhs/year for 2 years (Total 30 lakhs)",
                    "amount": 3000000,
                    "description": "Contingency budget for consumables and imported items for VLSI labs.",
                    "utilised_amount_lakh": 0,
                    "purchases_for": "",
                    "invoice": "Not attached",
                    "invoice_url": "",
                },
            ],
        )

    if not _has_table("budget_expenses"):
        op.create_table(
            "budget_expenses",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("head", sa.Text(), nullable=False),
            sa.Column("budget_lakh", sa.Float(), nullable=False, server_default="0"),
            sa.Column("expenses_description", sa.Text(), nullable=True),
            sa.Column("utilized_lakh", sa.Float(), nullable=False, server_default="0"),
            sa.Column("balance_lakh", sa.Float(), nullable=False, server_default="0"),
            sa.Column("vendor", sa.String(length=255), nullable=True),
            sa.Column("date", sa.String(length=32), nullable=True),
            sa.Column("amount", sa.Float(), nullable=False, server_default="0"),
            sa.Column("invoice", sa.String(length=512), nullable=True),
            sa.Column("invoice_url", sa.String(length=1024), nullable=True),
            sa.Column("status", sa.String(length=32), nullable=False, server_default="Pending"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        expenses = sa.table(
            "budget_expenses",
            sa.column("id", sa.Integer),
            sa.column("head", sa.Text),
            sa.column("budget_lakh", sa.Float),
            sa.column("expenses_description", sa.Text),
            sa.column("utilized_lakh", sa.Float),
            sa.column("balance_lakh", sa.Float),
            sa.column("vendor", sa.String),
            sa.column("date", sa.String),
            sa.column("amount", sa.Float),
            sa.column("invoice", sa.String),
            sa.column("invoice_url", sa.String),
            sa.column("status", sa.String),
        )
        op.bulk_insert(
            expenses,
            [
                {
                    "id": 1,
                    "head": "Internal engagements (Refreshment and other related Expenses for department/Centre faculty Meetings, Seminars, official Lunch/ Dinners etc.)",
                    "budget_lakh": 1.5,
                    "expenses_description": "4504 / April 2026 / 8654 / May 2026 / 20444 / May 2026",
                    "utilized_lakh": 0.34,
                    "balance_lakh": 1.16,
                    "vendor": "ECE Department",
                    "date": "2026-04-01",
                    "amount": 34000,
                    "invoice": "Not attached",
                    "invoice_url": "",
                    "status": "Approved",
                },
                {
                    "id": 2,
                    "head": "Expenditure on student & faculty recruitment",
                    "budget_lakh": 0.5,
                    "expenses_description": "",
                    "utilized_lakh": 0,
                    "balance_lakh": 0.5,
                    "vendor": "ECE Department",
                    "date": "2026-04-01",
                    "amount": 0,
                    "invoice": "Not attached",
                    "invoice_url": "",
                    "status": "Pending",
                },
                {
                    "id": 3,
                    "head": "Provision of support to students of department/centre for Presenting at conferences/events etc. including organizing events",
                    "budget_lakh": 0.68,
                    "expenses_description": "",
                    "utilized_lakh": 0,
                    "balance_lakh": 0.68,
                    "vendor": "ECE Department",
                    "date": "2026-04-01",
                    "amount": 0,
                    "invoice": "Not attached",
                    "invoice_url": "",
                    "status": "Pending",
                },
                {
                    "id": 4,
                    "head": "External engagement (Expenditure on Travel and stay of Experts/Visitors for a seminar or otherwise for Interaction and payment of honorarium, Gifts/Mementoes/Souvenirs to Guest/Speakers/faculty and for workshops/Seminars/Conferences etc.)",
                    "budget_lakh": 0.5,
                    "expenses_description": "",
                    "utilized_lakh": 0,
                    "balance_lakh": 0.5,
                    "vendor": "ECE Department",
                    "date": "2026-04-01",
                    "amount": 0,
                    "invoice": "Not attached",
                    "invoice_url": "",
                    "status": "Pending",
                },
                {
                    "id": 5,
                    "head": "Consumables & Non-consumables",
                    "budget_lakh": 0.5,
                    "expenses_description": "",
                    "utilized_lakh": 0,
                    "balance_lakh": 0.5,
                    "vendor": "ECE Department",
                    "date": "2026-04-01",
                    "amount": 0,
                    "invoice": "Not Attached",
                    "invoice_url": "",
                    "status": "Pending",
                },
                {
                    "id": 6,
                    "head": "Industry Day/ECE Day",
                    "budget_lakh": 1,
                    "expenses_description": "",
                    "utilized_lakh": 0,
                    "balance_lakh": 1,
                    "vendor": "ECE Department",
                    "date": "2026-04-01",
                    "amount": 0,
                    "invoice": "Not attached",
                    "invoice_url": "",
                    "status": "Pending",
                },
                {
                    "id": 7,
                    "head": "Department publicity (alumni meet, hackathons/student club activities/ competitions/ IEEE advertisements/ professional videos etc.)",
                    "budget_lakh": 0.5,
                    "expenses_description": "",
                    "utilized_lakh": 0,
                    "balance_lakh": 0.5,
                    "vendor": "ECE Department",
                    "date": "2026-04-01",
                    "amount": 0,
                    "invoice": "Not attached",
                    "invoice_url": "",
                    "status": "Pending",
                },
                {
                    "id": 8,
                    "head": "Department development budget",
                    "budget_lakh": 2.5,
                    "expenses_description": "130000 / April 2026 / 9359 / May 2026",
                    "utilized_lakh": 1.4,
                    "balance_lakh": 1.1,
                    "vendor": "ECE Department",
                    "date": "2026-04-01",
                    "amount": 140000,
                    "invoice": "Not attached",
                    "invoice_url": "",
                    "status": "Approved",
                },
            ],
        )

    if not _has_table("budget_inventory"):
        op.create_table(
            "budget_inventory",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("item", sa.String(length=255), nullable=False, server_default="Inventory Purchase"),
            sa.Column("category", sa.String(length=255), nullable=False),
            sa.Column("quantity", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("quantity_given", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("location", sa.String(length=255), nullable=True),
            sa.Column("purchase_date", sa.String(length=32), nullable=True),
            sa.Column("amount", sa.Float(), nullable=False, server_default="0"),
            sa.Column("invoice", sa.String(length=512), nullable=True),
            sa.Column("invoice_url", sa.String(length=1024), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_budget_inventory_category", "budget_inventory", ["category"])
        inventory = sa.table(
            "budget_inventory",
            sa.column("id", sa.Integer),
            sa.column("item", sa.String),
            sa.column("category", sa.String),
            sa.column("quantity", sa.Integer),
            sa.column("quantity_given", sa.Integer),
            sa.column("location", sa.String),
            sa.column("purchase_date", sa.String),
            sa.column("amount", sa.Float),
            sa.column("invoice", sa.String),
            sa.column("invoice_url", sa.String),
        )
        op.bulk_insert(
            inventory,
            [
                {
                    "id": 1,
                    "item": "Books",
                    "category": "Tools",
                    "quantity": 3,
                    "quantity_given": 0,
                    "location": "Not specified",
                    "purchase_date": "2026-03-18",
                    "amount": 3467,
                    "invoice": "Not Attached",
                    "invoice_url": "",
                },
                {
                    "id": 2,
                    "item": "Inventory Purchase",
                    "category": "Books",
                    "quantity": 4,
                    "quantity_given": 2,
                    "location": "Not specified",
                    "purchase_date": "2026-06-18",
                    "amount": 234,
                    "invoice": "Not Attached",
                    "invoice_url": "",
                },
            ],
        )


def downgrade() -> None:
    if _has_table("budget_inventory"):
        op.drop_index("ix_budget_inventory_category", table_name="budget_inventory")
        op.drop_table("budget_inventory")
    if _has_table("budget_expenses"):
        op.drop_table("budget_expenses")
    if _has_table("budget_income"):
        op.drop_index("ix_budget_income_financial_year", table_name="budget_income")
        op.drop_table("budget_income")
